name: Deploy website to apache2

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    environment: production 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v3
        with:
            version: 10.33.0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18.19.1
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.33.0
          run_install: true

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: fix
        run: pnpm exec eslint --fix .

      - name: Build Project
        run: pnpm build

      - name: Deploy to Apache2 and copy config.js
        run: |
          sudo cp -r dist/* /var/www/html/
          sudo cp /home/jenish/config.js /var/www/html
          sudo systemctl restart apache2
          echo "copied file of config.js must be changed for other systems as it is specific to my self-runner"
